Document: pixelann
Title: Debian pixelann Manual
Author: <insert document author here>
Abstract: This manual describes what pixelann is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pixelann/pixelann.sgml.gz

Format: postscript
Files: /usr/share/doc/pixelann/pixelann.ps.gz

Format: text
Files: /usr/share/doc/pixelann/pixelann.text.gz

Format: HTML
Index: /usr/share/doc/pixelann/html/index.html
Files: /usr/share/doc/pixelann/html/*.html
